language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - apc
  - memcache

before_script:
  - sh -c "if [ `php-config --vernum` -ge 50500 ] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu ; else echo 'extension="apc.so"' >> ./tests/travis/php.ini ;fi"
  - phpenv config-add ./tests/travis/php.ini
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit